server:
  port: 8082

spring:
  application:
    name: shoppingcarts-service
  data:
    mongodb:
      database: shoppingcarts
      port: 27017
      host: shoppingcarts-mongo

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
    nonSecurePort: 8082